=== hamiguazzz/WordsTracer/src/hamiguazzz/database/core/database.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        xmlns="http://www.github.com/hamiguazzz"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.github.com/hamiguazzz"
        elementFormDefault="qualified"
>

    <xs:simpleType name="column_data_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="varchar"/>
            <xs:enumeration value="char"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="unsigned"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="datetime"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="column_data_length">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="65535"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="column_type">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="codename" type="xs:string" use="required"/>
        <xs:attribute name="type" type="column_data_type" use="required"/>
        <xs:attribute name="size" type="column_data_length" default="255"/>
    </xs:complexType>

    <xs:complexType name="table_type">
        <xs:sequence>
            <xs:element name="column" type="column_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="codename" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="database_type">
        <xs:sequence>
            <xs:element name="table" type="table_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="codename" type="xs:string"/>
        <xs:attribute name="encoding" type="xs:string" default="utf8"/>
        <xs:attribute name="sort" type="xs:string" default="utf8_general_ci"/>
    </xs:complexType>

    <xs:element name="database" type="database_type"/>

</xs:schema>

=== hamiguazzz/WordsTracer/dataStructure/words.xml
<?xml version="1.0" encoding="utf-8" ?>
<database
        xmlns="http://www.github.com/hamiguazzz"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.github.com/hamiguazzz file://database.xsd"
        name="wordlist">
    <table name="words" codename="words">
        <column name="word" codename="word" type="varchar" size="64"/>
        <column name="simple_meaning" codename="simple_meaning" type="varchar"/>
        <column name="frequency" codename="frequency" type="unsigned" size="64"/>
        <column name="meanings_zh" codename="means" type="varchar" size="2048"/>
        <column name="meanings_en" codename="meaningEns" type="varchar" size="12000"/>
        <column name="pronunciation_en" codename="pronunciation_en" type="varchar" size="128"/>
        <column name="pronunciation_am" codename="pronunciation_am" type="varchar" size="128"/>
        <column name="exchanges" codename="exchanges" type="varchar"/>
        <column name="tags" codename="tags" type="varchar" size="127"/>
        <column name="relative" codename="relative" type="varchar"/>
        <column name="last_update_time" codename="lastUpdateTime" type="datetime" size="0"/>
    </table>
</database>

=== hamiguazzz/WordsTracer/dataStructure/traces.xml
<?xml version="1.0" encoding="utf-8" ?>
<database
        xmlns="http://www.github.com/hamiguazzz"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.github.com/hamiguazzz file://database.xsd"
        name="wordlist">
    <table name="trace" codename="trace">
        <column name="word" codename="word" type="varchar" size="64"/>
        <column name="progress" codename="progress" type="unsigned" size="16"/>
        <column name="easy" codename="easy" type="unsigned" size="16"/>
        <column name="forget" codename="forget" type="unsigned" size="16"/>
        <column name="last_read_time" codename="lastReadTime" type="datetime" size="0"/>
        <column name="first_read_time" codename="firstReadTime" type="datetime" size="0"/>
        <column name="tags" codename="tags" type="varchar" size="128"/>
    </table>
</database>
